### ISSUE TITLE
Flake Inputs Spits Out Errors 

### ISSUE THREAD

**Issue by DAnaselo** [Svenum/Solaar-Flake#2]
Non of These Worked When i Put Them Into Inputs
url = "https://github.com/Svenum/Solaar-Flake/latest; # For latest stable version
#url = "https://github.com/Svenum/Solaar-Flake/release-1.1.11; # uncomment line for version 1.1.11
#url = "https://github.com/Svenum/Solaar-Flake/main; # Uncomment line for latest unstable version

The Only Way I Could Made One Work Is By Doing This 
url = "github:Svenum/Solaar-Flake"; # For latest stable version

And oh yeah btw after doing that solaar doesn't display anything from my 2 logitech devices "its a blank select menu"

**Comment by Svenum** [comment]
Sorry, thats my bad. You are right it should be:
` url= "github:Svenum/Solaar-Flake/latest`
and NOT:
`url = "https://github.com/Svenum/Solaar-Flake/latest`
I Update the doku.

**Comment by Svenum** [comment]
I have updated the README.md. The other issue is not part of my work, for that please make an issue in the Solaar Repository: https://github.com/pwr-Solaar/Solaar/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=

**Comment by Svenum** [comment]
I will close this issue @DAnaselo. If there are still any problems, simply reopen it :smiley:
